### ISSUE TITLE
Create logo/icon for sci

### ISSUE THREAD

**Issue by lread** [borkdude/sci#129]
Same idea as https://github.com/borkdude/jet/issues/50

Will share ideas here.

**Comment by lread** [comment]
sci stands for "Small Clojure Interpreter" with sub description of "A tiny implementation of Clojure in Clojure".

A mini solo brainstorm to get ideas rolling (please chip in if you can think of more)
* small, tiny - maybe a child, boy or girl
* clojure - we can't use clojure logo, so maybe parentheses, or lambda. suppose we can use clojure color scheme though
* clojure in clojure - hmmm... not turtles all the way down... maybe just a turtle on a turtle
* interpreter - this one is hard to visualize, maybe reading, studying, analyzing.

**Sample 1 - sci as  parentheses**

![sci-parentheses1](https://user-images.githubusercontent.com/967328/67788889-7ab8d180-fa49-11e9-8c77-a1ff2ed63009.png)

**Comment by borkdude** [comment]
Already like this one :). Keep 'em coming :)

**Comment by lread** [comment]
**Sample 2 - happy boy manning conveyor belt**
Here we have a **small** boy joyfully manning the **interpreter** conveyor belt.  Employed the **clojure** colors.  Lowercase sci also feels **small**. The boxes might might subtly convey **clojure in clojure**.

![sci-happy-boy-conveyer-belt](https://user-images.githubusercontent.com/967328/67810416-f417ea80-fa70-11e9-8e3b-e61580c779f4.png)

I like how the i seems happy.

I think this could also work without the boy. Or the boy could be altered to a borkdude likeness 🙂.

**Comment by borkdude** [comment]
@lread Not really a fan of 2, sorry :-).

Expanding on sample 1, to have a Clojure-in-Clojure effect, maybe the parens which form the dot on the i maybe could wrap the entire name? and then remove the dot from the capital I I guess.

**Comment by lread** [comment]
Too cute maybe?  Gonna include conveyor belt only version, because I like it. 🙂 

**Sample 3 - conveyor belt**

![sci-conveyer-belt](https://user-images.githubusercontent.com/967328/67812497-b4073680-fa75-11e9-9fdb-95fcc02363db.png)

**Comment by lread** [comment]
**Sample 4 - sci as parens in parens**
This is a bit tricky, we don't want the wrapping parens to look like a letter (the c is a parens after all). Maybe making the enclosing parens a bit taller and thinner would help with that:

![sci-enclosed-in-parens](https://user-images.githubusercontent.com/967328/67813078-0a28a980-fa77-11e9-9493-2eb6afb35893.png)

**Comment by borkdude** [comment]
@lread That's what I had in mind as well, maybe make them larger and more round so they would almost touch each other's ends, so it's a little universe in which sci lives.

**Comment by lread** [comment]
Something like this?

**Sample 5 - sci as parens fully enclosed in parens**

![sci-fully-enclosed](https://user-images.githubusercontent.com/967328/67814550-b0c27980-fa7a-11e9-9eba-890a82b57922.png)

**Comment by borkdude** [comment]
@lread Something like that yes! And then re-introduce the Clojure colors, so the parens in green for example. Or different colors, actually a lot like the CLJS logo: https://github.com/cljs/logo

**Comment by borkdude** [comment]
@lread But keep the form of the parens (so varying in thickness), not making it as regular as the CLJS logo.

**Comment by lread** [comment]
**Sample 6a - sci enclosed colored**
We don't have the same symmetry that "cl" "js" offers, so I opted to use the full clojure logo pallette:
 
![sci-enclosed-colored](https://user-images.githubusercontent.com/967328/67815145-76f27280-fa7c-11e9-9a28-50b516557bc9.png)

If this is something you are leaning toward, we can try variations with same colors, if need be.  For example I'm thinking that bright green is a bit much.

**Sample 6b - enclosed colored**

![sci-enclosed-colored-b](https://user-images.githubusercontent.com/967328/67815354-16b00080-fa7d-11e9-8abd-5beb990483f5.png)

**Sample 6c - enclosed colored**

![sci-enclosed-colored-c](https://user-images.githubusercontent.com/967328/67815486-6c84a880-fa7d-11e9-9dc9-debe91445163.png)

variation c has a nice symmetry.

**Comment by borkdude** [comment]
6c has a nice symmetry, but somehow I like 6b the best. maybe I like a little bit of irregularity, like 2 for Tuesdays you know.

**Comment by borkdude** [comment]
@lread I like them all, so let's go with the symmetric one.

Can the surrounding parens become bigger in size or thinner in thickness, so the letters have more space or look like they have more space?

**Comment by borkdude** [comment]
@lread I like the last one. With that one, can you make the letters smaller compared to the circle?

**Comment by borkdude** [comment]
6h looks good to me.

**Comment by lread** [comment]
ok good. Noticed that the s looks a little close to the c, here's 6h again followed by 6h-1.

![sci-6h](https://user-images.githubusercontent.com/967328/67877887-c8e4d800-fb10-11e9-8531-0776b5a75f84.png)
![sci-6h-1](https://user-images.githubusercontent.com/967328/67877890-caae9b80-fb10-11e9-9b7e-2a1748c4f593.png)

**Comment by lread** [comment]
I am currently wondering if there is some way we can subtly style the i.

**Comment by borkdude** [comment]
@lread Maybe the right corners can be round-ish?

**Comment by lread** [comment]
Oh to make it paren-ish?  Let's try!

**Sample 7 - i needs love?**

![sci-7](https://user-images.githubusercontent.com/967328/67880568-427ec500-fb15-11e9-9f12-c701cfa3889f.png)

Ya, good idea, that seems better to me, you?

Actually maybe the i can now gain some width:

**Sample 7b - i needs some love and some carbs?**

![sci-7b](https://user-images.githubusercontent.com/967328/67881497-fc2a6580-fb16-11e9-8a52-52fde3f8ddcc.png)

**Comment by borkdude** [comment]
My wife and I both like 7a (the first) better

**Comment by lread** [comment]
Yes, I agree with you and your wife.
