### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by viebel** [borkdude/sci#15]
I really love this project and I hope to be able to contribute.
in the README:
> You want to evaluate code from user input, but eval isn't safe or simply doesn't work.

Could you elaborate about what are the situations in which `eval` doesn't work?
I guess that when we compile a clojure program with GraalVM, `eval` doesn't work. Right?

Is it something essential to GraalVM? Could `eval` be available some day on GraalVM? Could we image a super fast Clojure REPL?

Please share as much details as you can ...

**Comment by borkdude** [comment]
@viebel This library was extracted from [babashka](https://github.com/borkdude/babashka), so that is the main use case for it right now, but I thought it would be nice to also support other platforms while I'm at it. If I understand correctly, `eval` doesn't work on GraalVM because GraalVM is based on tree-shaking, much like advanced compilation in ClojureScript. That's at least how I understand it.

**Comment by Kah0ona** [comment]
So maybe this is a dumb question, but is SCI then a sort of re-implementation of `eval` precisely to circumvent those issues?

**Comment by borkdude** [comment]
@Kah0ona All SCI does is interpret EDN expressions. So `'(+ 1 2 3)` becomes something like `(apply + [1 2 3])` at runtime.

**Comment by viebel** [comment]
In the JVM based Clojure, `eval` is implemented in Java.
In (Self-hosted) Clojurescript, `eval` (called `eval-str`) is implemented in Clojurescript. The code in `sci` is similar to the code involved  in `eval-str`.

Look for example at[ the emit function for an if expression](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/compiler.cljc#L633).


The main differences are:
1. `eval-str` produces javascript code and the evaluated it with the javascript `eval` function, while in `sci`, `eval` evaluates the code directly
2. `eval-str` first analyzes the code and creates an AST (Abstract Syntax Tree), while in `sci`, `eval` works at the edn level.

@borkdude, feel free to correct me and/or to add further explanations. The topic of compilers and interpreters really interest me but I don't have lot of knowledge.

**Comment by borkdude** [comment]
@viebel I think you're spot on.

**Comment by Kah0ona** [comment]
Makes a lot of sense, thanks.
