### ISSUE TITLE
Binding/allowing a whole namespace?

### ISSUE THREAD

**Issue by actonDev** [borkdude/sci#158]
I would like to know if you can allow a whole namespace. Let's say I have a `app.script.api` namespace and I want all its functions available inside sci. how would I do that?
I get that you can either bind one by one
``` clj
{:bindings
 {'api/fn1 app.script.api/fn1
  'api/fn2 app.script.api/fn2}}
```
Or (even more complicated) allow the namespace to be required with `{:namespaces` but from my understanding in this syntax you also bind functions that will be available in this "required-able" namespace.

..At least this is my understanding

PS thanks for this library, great stuff :)

**Comment by borkdude** [comment]
@actonDev This is documented in the README:

It is also possible to provide namespaces which can be required:
```
user=> (def opts {:namespaces {'foo.bar {'println println}}})
user=> (sci/eval-string "(require '[foo.bar :as lib]) (lib/println \"hello\")" opts)
hello
nil
```

There is no option to just copy a namespace from the host environment into sci. But you can probably do that using `ns-publics` in Clojure on the JVM without too much trouble.

**Comment by borkdude** [comment]
@actonDev I see that I haven't documented the `:aliases` option which allow you to define an alias beforehand: `{:aliases '{lib foo.bar}}`.

**Comment by actonDev** [comment]
Would aliases expose the whole namespace?
By using aliases I get a `Could not resolve symbol: api/fn1 [at line 1, column 1]`

I see from your first comment that I could manually create the binding with the usage of `(ns-publics)` (thanks btw, didn't know this function :) )

So I would either go that way, or indeed the alias is supposed to do all this?

**Comment by borkdude** [comment]
@actonDev No, `:aliases` only defines an alias, so the user can use it immediately without writing a require first.
