### ISSUE TITLE
Retain metadata on namespaces and function definitions

### ISSUE THREAD

**Issue by wilkerlucio** [borkdude/sci#269]
**Is your feature request related to a problem? Please describe.**
The problem is that I would like to make decisions based on the var metadata of namespaces and functions, currently, this information is not visible in the SCI environment.

**Describe the solution you'd like**
I like to have this information exposed in the symbol metadata present on the `:namespace` keys of the environment. So a code like this would work:

```clojure
(let [env          (atom {})
      user-library (pr-str
                     '(do
                        (ns ^:user-ns some.new-ns)

                        (defn ^:user-fn my-custom-fn [x] (str x " augmented"))))]
  (sci/eval-string user-library {:env env :namespaces standard-lib-ns :bindings {'% {}}})
  (->> @env :namespaces keys (filter #{'some.new-ns}) first meta) ; => {:user-ns true}
  (-> @env :namespaces (get 'some.new-ns) first key meta) ; => {:user-fn true}
  )
```

**Comment by borkdude** [comment]
Namespaces currently don't keep metadata, I'll fix that.
Vars created by users however do retain metadata:

```
user=> (require '[sci.core :as sci])
nil
user=> (sci/eval-string "(defn ^:cool-fn foo [] :foo) (meta #'foo)")
{:ns #object[sci.impl.vars.SciNamespace 0x5f3f3d00 "user"], :name foo, :cool-fn true, :file nil, :end-column 29, :column 1, :line 1, :end-line 1, :arglists ([])}
```

**Comment by wilkerlucio** [comment]
Thanks for the clarification, I was trying to get the meta from the symbol key, but as you mention its available on the var itself 👍

**Comment by borkdude** [comment]
This now works:

```
$ lein run "(ns ^{:a 1} foo {:b 1}) (meta *ns*)"
{:line 1, :column 5, :end-line 1, :end-column 16, :a 1, :b 1}
```

TODO:

- [ ] make namespace objects singletons

  ```
  lein run "(ns ^{:a 1} foo {:b 1}) (meta *ns*) (ns bar) (meta (the-ns 'foo))"
  ```

**Comment by wilkerlucio** [comment]
What's that about that map with `{: 1}` after the namespace, is that something supported by Clojure too?

**Comment by borkdude** [comment]
@wilkerlucio Yes, that's an attribute map (which is just another name for metadata).

**Comment by wilkerlucio** [comment]
Cool, in this implementation, its also possible to get the meta from the `:namespaces` part of the SCI env?

**Comment by borkdude** [comment]
@wilkerlucio I don't recommend depending on the internal structure of the sci env atom. You can get the metadata like this (when this feature is done):

```
(def env (atom {}))
(sci/eval-string "(ns foo {:a 1})" {:env env})
(sci/eval-string "(meta (the-ns 'foo))" {:env env}) ;;=> {:a 1}
```

**Comment by wilkerlucio** [comment]
Ok, makes sense, thanks for the clarification.

**Comment by wilkerlucio** [comment]
I still want to use the `:namespaces` to iterate over all user defined namespaces, can I count on the `:namespaces` to stay consistent on the `env`? (as a map)

**Comment by borkdude** [comment]
@wilkerlucio You can get all namespaces with `(all-ns)` and all public vars with `ns-publics`:

```
 (sci/eval-string "(-> (all-ns) first ns-publics)")
```

**Comment by borkdude** [comment]
@wilkerlucio I'm not 100% done yet (fixing some edge cases for built-in namespaces) but this should now work in the `namespace-meta` branch:

```
$ lein run "(ns ^{:a 1} foo {:b 1}) (meta *ns*) (ns bar) (meta (the-ns 'foo))"
{:line 1, :column 5, :end-line 1, :end-column 16, :a 1, :b 1}
```
So I think combined with `all-ns` you can then fetch the metadata for all user-defined namespaces. Can you test a bit with this maybe?

**Comment by borkdude** [comment]
TODO
- [ ] this should probably return the empty set:

```
(set/difference (sci/eval-string "(set (all-ns))" (sci/eval-string "(set (all-ns))")))
```

**Comment by borkdude** [comment]
@wilkerlucio I now fixed the above one. You can detect newly created namespaces like this now:

```
$ clojure -e "(require '[clojure.set :as set] '[sci.core :as sci]) (set/difference (sci/eval-string \"(ns foo) (set (all-ns))\") (sci/eval-string \"(set (all-ns))\"))"
#{#object[sci.impl.vars.SciNamespace 0x322b09da "foo"]}
```

**Comment by wilkerlucio** [comment]
Cool, that sounds right! Thanks for iterating so quickly on this :)

**Comment by borkdude** [comment]
@wilkerlucio This feature is now deploying as `0.0.13-alpha.11` on CI. Let me know if there are any issues, then I'll re-open the issue if needed.
