### ISSUE TITLE
Implement protocols

### ISSUE THREAD

**Issue by borkdude** [borkdude/sci#279]
Work in progress in the `defprotocol` branch.

Todo:

- [x] defprotocol
- [x] extend-protocol
- [x] defrecord + protocols
- [x] extend
- [x] extend-type
- [x] support docstring in defprotocol:

```
(defprotocol Fly
  "A simple protocol for flying"
  (fly [this] "Method to fly"))
```

- [x] extends?
- [x] fully qualify protocol symbols / test with different namespaces
- [ ] `instance?` should work on protocol checks: `(instance? clojure.spec.alpha.Spec x)`
- [x] test more examples from clojuredocs
- [x] test libs: spec, hiccup

**Comment by cldwalker** [comment]
I think this would be valuable as I've tried using a couple libraries in bb scripts and found the lack of protocol prevented their usage. https://github.com/clj-commons/camel-snake-kebab was one I tried

**Comment by cldwalker** [comment]
Two more namespaces/libraries that would be great to have:
- clojure.datafy
-  https://github.com/aysylu/loom via borkdude/babashka#415

**Comment by borkdude** [comment]
Another library with defprotocol: https://github.com/clojure/tools.namespace
See borkdude/babashka#424

**Comment by borkdude** [comment]
Made some progress in the defprotocol branches of babashka and sci.

- The camel-snake-kebab library now fully works.
- The loom.graph namespace works, but .alg doesn't because it depends on the priority-map library which uses deftype. 

TODO: try datafy, test.check, tools.namespace

**Comment by cldwalker** [comment]
@borkdude Confirmed all the same behaviors in the above libraries with 0.1.1. Thanks! To get closer to test.check working, I could add the `*unchecked-math*` binding to main.clj if you'd like

**Comment by borkdude** [comment]
Sure, go ahead.
