### ISSUE TITLE
Consider reimplementing dotimes without loop

### ISSUE THREAD

**Issue by brunchboy** [borkdude/sci#298]
**Is your feature request related to a problem? Please describe.**
I’m running sci with the `:termination-safe` preset, and my users wanted to be able to use `dotimes` for a finite loop, but this fails because it delegates to the forbidden `loop`. It’s possible to manually rewrite such code using `doseq` and `range`, but we could save people the surprise and effort.

**Describe the solution you'd like**
I was thinking we could simply provide an alternate implementation of `dotimes` which was implemented without `loop`, probably with `doseq` and `range` to avoid this issue.

**Describe alternatives you've considered**
As described above, we can simply have users do it themselves.

**Additional context**
I brought this idea up on the babashka channel of the clojurians slack, and Michiel agreed that it might be a useful enhancement. He suggested looking at the history of the macro .cljc file to see how a similar fix had already been made to `for`. A quick scan suggests it might be https://github.com/borkdude/sci/issues/141

This is an interesting problem so I may try my hand at a PR, but want to capture the issue first anyway, because given all the issues I am working on in my own projects, it might not be realistic that I will get around to working on this.

**Comment by borkdude** [comment]
@brunchboy I think the same fix that we applied for the `for` macro can also be applied to `dotimes`:

https://github.com/borkdude/sci/commit/cf8db779576d85c745d4d43e1df54582ea8b6484#diff-5a9a05f99b4c6e1b37f7f89cff8b3681

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/sci/commit/bce604b2147e4877d70a3dbe532ba00b4c2b5a19
