### ISSUE TITLE
Circular dependency between sci.impl.io and sci.impl.io

### ISSUE THREAD

**Issue by okilimnik** [borkdude/sci#300]
**version**

0.0.13-alpha.12

**platform**

jvm

**problem**

Circular dependency between sci.impl.io and sci.impl.io error when running refreshable tests with lein test-refresh

**repro**

Create a project which uses sci, write some dummy tests, try to run them with https://github.com/jakemcc/lein-test-refresh

**expected behavior**

Tests are run

**Comment by borkdude** [comment]
Unless you can reproduce this with a vanilla tool like the clojure CLI or leininigen which this project itself uses, I can't spend any time on looking at potential issues in other people's tooling.

**Comment by borkdude** [comment]
I have bumped the version to alpha.13 now (will be pushed to clojars in a few minutes). You could try again with that version and then work on a reproduction. I'll re-open when you come back with a good repro.
