### ISSUE TITLE
JavaScript interop: method calls not working?

### ISSUE THREAD

**Issue by cassiel** [borkdude/sci#312]
**version**

0.0.13-alpha.16

**platform**

macOS, using from Node.js.

**problem**

Cannot do method calls on JS objects passed in via bindings.

**repro**

This works (function callback):
`evalString("(f)", {bindings: {f: () => console.log("HELLO")}})`

This fails:
`evalString("(.f foo)", {bindings: {foo: {f: () => console.log("HELLO")}}})`

with: Mn [Error]: Method f on function k(a,b,c,d){this.u=a;this.A=b;this.l=c;this.C=d;this.o=16647951;this.F=139268} not allowed!

**expected behavior**

From the above: "HELLO".

**Comment by borkdude** [comment]
@cassiel For some reason the object is converted into a CLJS object. But this works:

```
> evalString("(.f (clj->js foo))", {classes: {allow: "all"}, bindings: {foo: {"f": () => console.log("HELLO")}}})
HELLO
```

I'll take a look.

**Comment by borkdude** [comment]
Fixed in `@borkdude/sci@0.0.13-alpha.17`:

```
> let { evalString } = require("@borkdude/sci");
undefined
> evalString("(.f foo)", {classes: {allow: "all"}, bindings: {foo: {"f": () => console.log("HELLO")}}})
HELLO
```

**Comment by cassiel** [comment]
Fantastically fast response: thank you! (This is for interop with Cycling '74 MaxMSP for audiovisuals.) Happy to test now or wait for the NPM update.

**Comment by borkdude** [comment]
@cassiel The NPM library is already updated.

**Comment by cassiel** [comment]
npm search still claiming alpha 13 - will fetch again.
