### ISSUE TITLE
Update Sci version on npm 

### ISSUE THREAD

**Issue by jeroenvandijk** [borkdude/sci#324]
@borkdude when you have time I would love to have an updated version of Sci on npm :pray: (https://www.npmjs.com/package/@borkdude/sci , latest version is still 0.0.13-alpha.18 should be 0.0.13-alpha.19)

You have added some improvements lately :sunglasses:. E.g. this should work now: 

```
sci.evalString('(js/alert "hi")',{classes:{allow:'all',js:window}})
```

**Comment by borkdude** [comment]
Done!
