### ISSUE TITLE
Support for with-redefs

### ISSUE THREAD

**Issue by cldwalker** [borkdude/sci#325]
Hi. I see #175 and #176 attempted to implement `with-redefs` but then disabled it. It would be awesome to include it for babashka given how powerful a testing tool it is

**Is your feature request related to a problem? Please describe.**
I'm looking to writing tests in babashka that use with-redefs. I'd also like to pull in [this testing library](https://github.com/circleci/bond) which relies on with-redefs

**Describe the solution you'd like**
A working with-redefs

**Describe alternatives you've considered**
I'm not aware of alternatives to this core fn

**Additional context**
If you describe what's needed to make this work, perhaps someone can help with this. I could try to take a shot at it some day

Cheers

**Comment by liquidz** [comment]
I've wrote a macro with features similar to `with-redefs` for babashka, but it would be more happy to support officially :)
https://github.com/liquidz/vim-iced/blob/64a15c893c0a92f9a33927100ee09872e5d21c3e/test/clj/command/iced/core_test.clj#L8-L14

**Comment by cldwalker** [comment]
Look forward to trying this. Thanks!
