### ISSUE TITLE
Eval'ing a string that is a number works for some numbers, but fails on others.

### ISSUE THREAD

**Issue by teesloane** [borkdude/sci#329]
**version**

`borkdude/sci "0.0.13-alpha.19"`

**platform**

JVM

**problem**

Eval'ing a string that is a number works for some numbers, but fails on others.

**repro**

```clojure
(sci/eval-string "03") ; => 3
(sci/eval-string "09") ; => exception
```

**expected behavior**

(sci/eval-string "09") ; => 9

**Comment by borkdude** [comment]
@teesloane What does evaluating `09` in Clojure do?

**Comment by teesloane** [comment]
Sorry, I didn't think to check. It fails with
```
NumberFormatException Invalid number: 09  clojure.lang.LispReader.readNumber (LispReader.java:342)
```
In case anyone was [wondering](https://groups.google.com/forum/#!topic/clojure/mpVaSp9OLso).  Learning every day.
