### ISSUE TITLE
Support for evaluating direct source code & fn*

### ISSUE THREAD

**Issue by ikitommi** [borkdude/sci#33]
Would be great if sci also supported also unqualified source code as input, maybe `sci.core/eval`? Currently, a hop via `pr-str` is needed. Also, `fn*` is not supported:

### Current status

sci:

```clj
((sci/eval-string (pr-str `#(< 10 % 18))) 17)
;Syntax error compiling at (src/malli/core.cljc:575:1).
;Could not resolve symbol: fn*
```

`eval`:

```clj
((eval `#(< 10 % 18)) 17)
; => true

((eval (read-string (pr-str `#(< 10 % 18)))) 17)
; => true
```

### Proposed:

```clj
((sci/eval `#(< 10 % 18)) 17)
; => true

((sci/eval-string (read-string (pr-str `#(< 10 % 18)))) 17)
; => true
```

**Comment by ikitommi** [comment]
Also:

```clj
(sci/eval-string (pr-str `(fn [x] (< 10 x 18))))
; Could not resolve symbol: clojure.core/fn
```

**Comment by borkdude** [comment]
@ikitommi I made some changes in https://github.com/borkdude/sci/commit/bf9337392f774f24f77856682a6ff79e274f9245 which should probably fix this.

**Comment by ikitommi** [comment]
Thanks! Still some resolving issues:

```clj
(mapv (partial (sci/eval-string `#(< 10 % 18))) [10 15 20])
; => [false true false]

(mapv (partial (sci/eval-string `#(and (int? %) (< 10 % 18)))) [10 15 20])
; Could not resolve symbol: clojure.core/and
```

**Comment by borkdude** [comment]
@ikitommi Should now work with change to master.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/sci/commit/73d0de59debe7a8acc4cb13e64f3cfe34baf0294

**Comment by ikitommi** [comment]
Awesome, thanks!
