### ISSUE TITLE
Metadata on defn is not evaluated

### ISSUE THREAD

**Issue by lread** [borkdude/sci#361]
**version**
recent pull from master, illustrations below are via bb v0.1.3

**platform**
macOS 10.15.5
Clojure 1.10.536 on JDK 11 for Clojure examples

**symptom**
While bringing in portions of test.check for an experimental project, I noticed that `defspec` was failing.

**repro**
While trying to diagnose why `defspec` was failing  noticed that the `defspec` macro is slightly different from clojure.test’s `deftest` in the way it attaches metadata. 

`defspec` [attaches metadata to a defn](https://github.com/clojure/test.check/blob/6363312afbbe8bb71d6cc9c64c627c98bb7e8b0d/src/main/clojure/clojure/test/check/clojure_test.cljc#L84) whereas `deftest` [attaches metadata it to a def](https://github.com/borkdude/babashka/blob/640ebce2420133060924522c860c1514b3d6fd60/src/babashka/impl/clojure/test.clj#L631).

Here’s my attempt at distilling the difference to a snippit in a file we'll call `metadefn.clj`:
```clojure
(require '[clojure.pprint :as pprint])

(println "metadata fn on def")
(def ^{:test (fn [] (println "hey there from a"))} a 1)
(pprint/pprint (meta #'a))
((:test (meta #'a)))

(println "\nmetadata fn on defn")
(defn ^{:test (fn [] (println "hey there from af"))} af [])
(pprint/pprint (meta #'af))
((:test (meta #'af)))
```

**expected behavior**
If we run the above snippit through Clojure, we get:
```
> clojure metadefn.clj 
metadata fn on def
{:test #object[user$fn__140 0x29f0802c "user$fn__140@29f0802c"],
 :line 4,
 :column 1,
 :file "/Users/lee/proj/oss/play/metadefn.clj",
 :name a,
 :ns #object[clojure.lang.Namespace 0x29a23c3d "user"]}
hey there from a

metadata fn on defn
{:test #object[user$fn__148 0x1a411233 "user$fn__148@1a411233"],
 :arglists ([]),
 :line 9,
 :column 1,
 :file "/Users/lee/proj/oss/play/metadefn.clj",
 :name af,
 :ns #object[clojure.lang.Namespace 0x29a23c3d "user"]}
hey there from af
```
**actual behavior**
Running the same snippit through sci (via babashka) gives us:
```
> bb metadefn.clj 
metadata fn on def
{:line 4,
 :column 6,
 :end-line 4,
 :end-column 53,
 :test #object[sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12684
               "0x7473ea2e"
               "sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12684@10f217700"],
 :name a,
 :ns #object[sci.impl.vars.SciNamespace "0x84a3722" "user"],
 :file "/Users/lee/proj/oss/play/metadefn.clj"}
hey there from a

metadata fn on defn
{:ns #object[sci.impl.vars.SciNamespace "0x84a3722" "user"],
 :name af,
 :file "/Users/lee/proj/oss/play/metadefn.clj",
 :end-column 60,
 :column 1,
 :line 9,
 :end-line 9,
 :arglists ([]),
 :test (fn [] (println "hey there from af"))}
java.lang.Exception: Cannot call (fn [] (println "hey there from af")) as a function. [at /Users/lee/proj/oss/play/metadefn.clj, line 11, column 1]
```
Notice for that the defn `:test` metadata was not evaluated whereas the def version was.

**Comment by borkdude** [comment]
I butchered the issue number in the commit, but this fixed it:

e1274a8a3a2d370553d349d9f3206d572c709f6b

Releasing as 0.1.1-alpha.2
