### ISSUE TITLE
Experiment with using sci and pgx to create Clojure plugin for PostgreSQL

### ISSUE THREAD

**Issue by borkdude** [borkdude/sci#373]
See discussion here: https://twitter.com/borkdude/status/1288590555585404935

**Comment by eeeebbbbrrrr** [comment]
https://github.com/zombodb/pgx

Link to pgx.

**Comment by borkdude** [comment]
Some results so far:

<img width="907" alt="Screenshot 2021-01-10 at 17 20 04" src="https://user-images.githubusercontent.com/284934/104133182-2f56be80-5382-11eb-92d5-34ea66a21a0e.png">
<img width="1432" alt="Screenshot 2021-01-10 at 18 13 58" src="https://user-images.githubusercontent.com/284934/104133183-31208200-5382-11eb-8e24-7b7ce4274b3c.png">

To build libsci:

https://github.com/borkdude/sci/blob/master/doc/libsci.md

The Rust code for integration with `pgx`:

``` rust
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]

use pgx::*;

use std::ffi::{CStr, CString};
use std::str::Utf8Error;
use std::{env, ptr};

pg_module_magic!();

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

static failed: &str = "failed";

fn eval(expr: String) -> Result<&'static str, Utf8Error> {
    unsafe {
        let mut isolate: *mut graal_isolate_t = ptr::null_mut();
        let mut thread: *mut graal_isolatethread_t = ptr::null_mut();

        graal_create_isolate(ptr::null_mut(), &mut isolate, &mut thread);

        let c_string = CString::new(expr).expect(failed);
        let ptr = c_string.as_ptr();

        let result = eval_string(
            thread as i64,
            ptr
        );

        CStr::from_ptr(result).to_str()
    }
}

#[pg_extern]
fn pgxsci(expr: String) -> &'static str {
    return eval(expr).unwrap();
}

#[cfg(any(test, feature = "pg_test"))]
mod tests {
    use pgx::*;

    #[pg_test]
    fn test_hello_pgxsci() {
        assert_eq!("Hello, pgxsci", crate::pgxsci());
    }

}

#[cfg(test)]
pub mod pg_test {
    pub fn setup(_options: Vec<&str>) {
        // perform one-off initialization when the pg_test framework starts
    }

    pub fn postgresql_conf_options() -> Vec<&'static str> {
        // return any postgresql.conf settings that are required for your tests
        vec![]
    }
}
```

**Comment by borkdude** [comment]
@eeeebbbbrrrr One issue: it seems `cargo pgx run pg13` doesn't pick up on `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH`:

```
borkdude@MBP2019 /tmp/pgxsci $ LD_LIBRARY_PATH=/Users/borkdude/Dropbox/dev/clojure/babashka/sci/libsci/target cargo pgx run pg13

    Stopping Postgres v13
building extension with features `pg13`
"cargo" "build" "--features" "pg13" "--no-default-features"
   Compiling pgxsci v0.0.0 (/private/tmp/pgxsci)
    Finished dev [unoptimized + debuginfo] target(s) in 2.40s

installing extension
     Copying control file to `/Users/borkdude/.pgx/13.0/pgx-install/share/postgresql/extension/pgxsci.control`
     Copying shared library to `/Users/borkdude/.pgx/13.0/pgx-install/lib/postgresql/pgxsci.so`
     Writing extension schema to `/Users/borkdude/.pgx/13.0/pgx-install/share/postgresql/extension/pgxsci--1.0.sql`
    Finished installing pgxsci
    Starting Postgres v13 on port 28813
    Re-using existing database pgxsci
psql (13.0)
Type "help" for help.

pgxsci=# SELECT cast(pgxsci(format('(cheshire.core/generate-string {:num %s :letter "%s", :reverse (clojure.string/reverse "%2$s")})', t.num, t.letter)) as json) FROM (VALUES (1, 'one'), (2, 'two'), (3, 'three')) AS t (num,letter);
ERROR:  could not load library "/Users/borkdude/.pgx/13.0/pgx-install/lib/postgresql/pgxsci.so": dlopen(/Users/borkdude/.pgx/13.0/pgx-install/lib/postgresql/pgxsci.so, 10): Library not loaded: /Users/borkdude/Dropbox/dev/clojure/babashka/sci/libsci.dylib
  Referenced from: /Users/borkdude/.pgx/13.0/pgx-install/lib/postgresql/pgxsci.so
  Reason: image not found
pgxsci=#
```

Compare with the cpp example from the linked libsci.md:

```
$ libsci/target/from_cpp "(+ 1 2 3)"
dyld: Library not loaded: /Users/borkdude/Dropbox/dev/clojure/babashka/sci/libsci.dylib
  Referenced from: /Users/borkdude/Dropbox/dev/clojure/babashka/sci/libsci/target/from_cpp
  Reason: image not found

$ DYLD_LIBRARY_PATH=libsci/target libsci/target/from_cpp "(+ 1 2 3)"
6
```

**Comment by borkdude** [comment]
When printing these env vars in the extension to a file, I see:

LD_LIBRARY_PATH: Err(NotPresent)DYLD_LIBRARY_PATH: Err(NotPresent), so they appear not to be propagated somewhere.

**Comment by borkdude** [comment]
Other env vars are propagated.

I might be hitting: https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html

**Comment by borkdude** [comment]
For sure now:

```
borkdude@MBP2019 ~/Dropbox/temp/pgxsci $ DYLD_LIBRARY_PATH=foobar bb -e '@(babashka.process/process ["bash" "-c" "echo ...$DYLD_LIBRARY_PATH..."] {:out :inherit}) nil'
......
borkdude@MBP2019 ~/Dropbox/temp/pgxsci $ FOO_PATH=foobar bb -e '@(babashka.process/process ["bash" "-c" "echo ...$FOO_PATH..."] {:out :inherit}) nil'
...foobar...
```

**Comment by eeeebbbbrrrr** [comment]
I wonder if what you should be doing instead is creating a static library for sci and then statically link to that with the pgx wrapper.  Then you'll have everything in your pgx extension .so.

I think this is a pretty common approach in the rust world.

**Comment by eeeebbbbrrrr** [comment]
```rust
fn eval(expr: String) -> Result<&'static str, Utf8Error> {
    unsafe {
        let mut isolate: *mut graal_isolate_t = ptr::null_mut();
        let mut thread: *mut graal_isolatethread_t = ptr::null_mut();

        graal_create_isolate(ptr::null_mut(), &mut isolate, &mut thread);

        let c_string = CString::new(expr).expect(failed);
        let ptr = c_string.as_ptr();

        let result = eval_string(
            thread as i64,
            ptr
        );

        CStr::from_ptr(result).to_str()
    }
}

#[pg_extern]
fn pgxsci(expr: String) -> &'static str {
    return eval(expr).unwrap();
}
```

You should probably change `eval()` to return `Result<String, Utf8Error>` so that you can free the pointer from the graal environment.  As it stands right now, you're leaking that pointer.  Leaking memory isn't considered undefined behavior, but it's definitely not good for a running Postgres system.  Also, passing around pointers allocated by some other blackbox system into Postgres could be dangerous.  It's not in this particular case because pgx will properly convert that `&'static str` into a Postgres-allocated text Datum, but it could be dangerous in other situations in that Postgres might want to free that pointer on your behalf, which it can't do b/c Postgres didn't allocate it.

**Comment by borkdude** [comment]
From a GraalVM chat from 2018:

> for setting rpath we don't have anything atm (but you can use chrpath (linux) or install_name_tool (darwin) for that).

Also see:

https://github.com/ros2/ros2/issues/457

**Comment by borkdude** [comment]
@eeeebbbbrrrr Thanks for the Rust feedback. Unfortunately it's not possible to create static binaries for other OS-es than linux at the moment. A workaround using `install_name_tool` to set the `rpath` may work.

**Comment by eeeebbbbrrrr** [comment]
yeah, I suppose you'd have to tie that into build.rs.  Make a copy of the libsci.so, run `install_name_tool` on that, and somehow teach cargo-pgx how to copy that .so alongside your extension .so during `cargo pgx run/install/package`.

**Comment by borkdude** [comment]
This worked!

From within the sci repo:

```
install_name_tool -id $PWD/libsci/target/libsci.dylib libsci/target/libsci.dylib
```

Then make a change in build.rs to it picks up the change and it works:

```
borkdude@MBP2019 ~/Dropbox/temp/pgxsci $ cargo pgx run pg13

    Stopping Postgres v13
building extension with features `pg13`
"cargo" "build" "--features" "pg13" "--no-default-features"
   Compiling pgxsci v0.0.0 (/Users/borkdude/Dropbox/temp/pgxsci)
    Finished dev [unoptimized + debuginfo] target(s) in 4.42s

installing extension
     Copying control file to `/Users/borkdude/.pgx/13.0/pgx-install/share/postgresql/extension/pgxsci.control`
     Copying shared library to `/Users/borkdude/.pgx/13.0/pgx-install/lib/postgresql/pgxsci.so`
     Writing extension schema to `/Users/borkdude/.pgx/13.0/pgx-install/share/postgresql/extension/pgxsci--1.0.sql`
    Finished installing pgxsci
    Starting Postgres v13 on port 28813
    Re-using existing database pgxsci
psql (13.0)
Type "help" for help.

pgxsci=# SELECT cast(pgxsci(format('(cheshire.core/generate-string {:num %s :letter "%s", :reverse (clojure.string/reverse "%2$s")})', t.num, t.letter)) as json) FROM (VALUES (1, 'one'), (2, 'two'), (3, 'three')) AS t (num,letter);
                    pgxsci
----------------------------------------------
 {"num":1,"letter":"one","reverse":"eno"}
 {"num":2,"letter":"two","reverse":"owt"}
 {"num":3,"letter":"three","reverse":"eerht"}
(3 rows)
```

**Comment by borkdude** [comment]
@eeeebbbbrrrr New version:

```
fn eval(expr: String) -> Result<String, Utf8Error> {
    unsafe {
        let mut isolate: *mut graal_isolate_t = ptr::null_mut();
        let mut thread: *mut graal_isolatethread_t = ptr::null_mut();

        graal_create_isolate(ptr::null_mut(), &mut isolate, &mut thread);

        let c_string = CString::new(expr).expect(failed);
        let ptr = c_string.as_ptr();

        let result = eval_string(
            thread as i64,
            ptr
        );

        let cstr = CStr::from_ptr(result).to_str()?;
        let ret = String::from(cstr);

        // This frees all memory allocated by the GraalVM runtime
        graal_tear_down_isolate(thread);

        return Ok(ret);
    }
}

#[pg_extern]
fn pgxsci(expr: String) -> String {
    return eval(expr).unwrap();
}
```

Also note the lines:

```        // This frees all memory allocated by the GraalVM runtime
        graal_tear_down_isolate(thread);
        ```
 
The minimal example runs in 3ms on my machine:

```
pgxsci=# select * from pgxsci('"foo"');
 pgxsci
--------
 foo
(1 row)

Time: 2.702 ms
```

**Comment by eeeebbbbrrrr** [comment]
You could probably make some kind of Graal struct which holds the graal environment pointers.  Keep it in a lazy_static and only need to initialize it once.

Also, you want `cargo pgx run pg13 --release` if you're going to try and measure performance.  `run'` default mode is debug.

**Comment by borkdude** [comment]
@eeeebbbbrrrr Good point about `--release`. I think the Graal "isolates" are kind of made for this purpose:

https://medium.com/graalvm/isolates-and-compressed-references-more-flexible-and-efficient-memory-management-for-graalvm-a044cc50b67e

Just spin one up, do some work, and tear it down. It should be relatively cheap, and also will prevent GC pauses...

This is something I would have to research more for trade-offs.

**Comment by eeeebbbbrrrr** [comment]
Fair enough.  

Time things with `--release` tho.  3ms is absurd for returning a 3 byte string.

**Comment by borkdude** [comment]
Yeah, `--release` doesn't change much. I will try the `lazy_static` approach as well.

**Comment by borkdude** [comment]
@eeeebbbbrrrr Hitting this now:

```
36 | / lazy_static! {
37 | |     static ref GRAALVM: Arc<Mutex<GraalVM>> = isolate();
38 | | }
   | |_^ `*mut __graal_isolatethread_t` cannot be sent between threads safely
```

**Comment by borkdude** [comment]
@eeeebbbbrrrr I think I "fixed" it...

```
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]

use pgx::*;

use std::ffi::{CStr, CString};
use std::str::Utf8Error;
use std::{env, ptr};

use std::sync::{Mutex, Arc};

#[macro_use]
extern crate lazy_static;

pg_module_magic!();

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

static failed: &str = "failed";

pub struct GraalVM {
    pub thread: i64,
}

unsafe fn isolate() -> Arc<Mutex<GraalVM>> {
    let mut isolate: *mut graal_isolate_t = ptr::null_mut();
    let mut thread: *mut graal_isolatethread_t = ptr::null_mut();
    graal_create_isolate(ptr::null_mut(), &mut isolate, &mut thread);

    let ptr = thread as i64;
    return Arc::new(Mutex::new(GraalVM {
        thread: ptr,
    }));
}

lazy_static! {
    static ref GRAALVM: Arc<Mutex<GraalVM>> = unsafe { isolate() };
}

fn eval(expr: String) -> Result<String, Utf8Error> {
    unsafe {
        let c_string = CString::new(expr).expect(failed);
        let ptr = c_string.as_ptr();

        let graalvm = GRAALVM.lock().unwrap();

        let result = eval_string(
            graalvm.thread,
            ptr,
        );

        let cstr = CStr::from_ptr(result).to_str()?;
        let ret = String::from(cstr);

        drop(graalvm);

        return Ok(ret);
    }
}

#[pg_extern]
fn pgxsci(expr: String) -> String {
    return eval(expr).unwrap();
}

#[cfg(any(test, feature = "pg_test"))]
mod tests {
    use pgx::*;

    #[pg_test]
    fn test_hello_pgxsci() {
        assert_eq!("Hello, pgxsci", crate::pgxsci());
    }

}

#[cfg(test)]
pub mod pg_test {
    pub fn setup(_options: Vec<&str>) {
        // perform one-off initialization when the pg_test framework starts
    }

    pub fn postgresql_conf_options() -> Vec<&'static str> {
        // return any postgresql.conf settings that are required for your tests
        vec![]
    }
}
```

This helps performance a lot (down to .5 ms, comparable to a "dummy" query which selects some literal VALUES).

**Comment by borkdude** [comment]
Maybe the downsize of this is that concurrent queries can now only use one shared isolate, which may be helped by having one isolate per thread. Not sure how that is done in Rust, but I already learned a lot today.

**Comment by eeeebbbbrrrr** [comment]
```rust
pub struct GraalVM {
    isolate: &'static graal_isolate_t
    thread: &'static graal_isolatethread_t,
}

impl GraalVM {
   fn new() -> Self {
       let mut isolate: *mut graal_isolate_t = ptr::null_mut();
        let mut thread: *mut graal_isolatethread_t = ptr::null_mut();

        graal_create_isolate(ptr::null_mut(), &mut isolate, &mut thread);

        GraalVM {
            isolate: isolate.as_ref().unwrap(),
            thread: thread.as_ref().unwrap(),
        }
   }

   fn eval(input: &str) -> String {
        let result = eval_string(
            self.thread as i64,
            ptr
        );

        let cstr = CStr::from_ptr(result).to_str()?;
        let ret = String::from(cstr);

        return ret; 
   }
}
```

Something like this.

**Comment by eeeebbbbrrrr** [comment]
or make self.thread an `i64` like you did (and I suppose you don't need `isolate` at all?).

And you shouldn't need a mutex or an Arc.  Just use a lazy static.  Probably need to add `#[derive(Clone, Copy)` to `GraalVM` if you change thread to an `i64`.

**Comment by eeeebbbbrrrr** [comment]
> Maybe the downsize of this is that concurrent queries can now only use one shared isolate, which may be helped by having one isolate per thread. Not sure how that is done in Rust, but I already learned a lot today.

There's no such thing as "concurrent queries".  Each Postgres backend will have its own Graal environment b/c each loads the pgx.so on-demand.

**Comment by eeeebbbbrrrr** [comment]
```rust
pub struct GraalVM {
    thread: i64,
}

impl GraalVM {
   fn new() -> Self {
        let mut thread: *mut graal_isolatethread_t = ptr::null_mut();

        graal_create_isolate(ptr::null_mut(), &mut isolate, &mut thread);

        GraalVM {
            thread: thread as i64
        }
   }

   fn eval(input: &str) -> String {
        let result = eval_string(self.thread, ptr);
        let cstr = CStr::from_ptr(result).to_str()?;
        let ret = String::from(cstr);

        // TODO:  how to free "result"?

        return ret; 
   }
}

**Comment by eeeebbbbrrrr** [comment]
yeah, the above will probably just work and not need a lock at all.

**Comment by borkdude** [comment]
@eeeebbbbrrrr Beautiful, thanks for the improvements. 

There are no "multiple threads" reusing the same isolate when writing an extension like this? So you don't even have to think about things like thread-safety? I'm surprised to learn this.

**Comment by eeeebbbbrrrr** [comment]
Postgres does not use threads.  At all.  Period.  Likely never will.  It's inherently not-thread-safe.  So while you still gotta fight with the Rust compiler, none of it really matters.

**Comment by borkdude** [comment]
@eeeebbbbrrrr Does this mean there is always only one query running at the same time?

**Comment by eeeebbbbrrrr** [comment]
per backend, yes.  Every new connection to Postgres is a brand new process.

**Comment by borkdude** [comment]
Ah, so backend = connection. This makes sense. And when using a connection pool of n connections, there will be n isolates.

**Comment by eeeebbbbrrrr** [comment]
In a way, that should be obvious b/c how would you get a single psql session to run two queries at once?  You can't b/c it's not a thing.  ;)

**Comment by eeeebbbbrrrr** [comment]
> Ah, so backend = connection. This makes sense. And when using a connection pool of n connections, there will be n isolates.

Yeppers.

**Comment by eeeebbbbrrrr** [comment]
oh, and then your pgextern func would look like:

```rust
#[pg_extern]
fn pgxsci(input: &str) -> String {
    GRAALVM.eval(input)
}
```

**Comment by eeeebbbbrrrr** [comment]
next you need to make a procedural language handler.  You're free to use my not-yet-released pl/rust as a starting point: https://github.com/zombodb/plrust

**Comment by borkdude** [comment]
I think it might be challenging to convert from Postgres types/pointer/thingies to Rust and then to things that are known to Clojure. But serializing everything via JSON is always an escape hatch...

@eeeebbbbrrrr Do you have a working end to end tests?

**Comment by borkdude** [comment]
@eeeebbbbrrrr I posted all the code so far in this repo: https://github.com/borkdude/plsci and also made you a collaborator.

**Comment by borkdude** [comment]
Let's create individual issues over there and close this one.
