### ISSUE TITLE
with-redefs doesn't redef core fns

### ISSUE THREAD

**Issue by cldwalker** [borkdude/sci#375]
Hi. I'm using with-redefs for a testing library and came across the following bug:

**version**

Version which comes with bb 0.1.3

**platform**

Mac binary

**problem**

with-redefs is unable to redef a clojure.core fn

**repro**

```
;; Doesn't return Hi
=> (with-redefs [spit (constantly "Hi")] (spit "file" "yolo"))
nil
;; Define fn with same name as clojure.core fn
=>  (defn spit [& args] (prn args))
nil
;; Behaves correctly now that spit is defined in ns
=> (with-redefs [spit (constantly "Hi")] (spit "file" "yolo"))
"Hi"
```

**expected behavior**

I expected to be able to redef a clojure.core fn as clojure does

**Comment by borkdude** [comment]
I think this may be due to an optimization, but maybe that optimization isn't worth it. I'll take a look.

**Comment by borkdude** [comment]
Undoing the performance optimization (which is effectively the same as direct linking in Clojure):

```
(time (sci/eval-string "(dotimes [_ 1000000] (+ (/ 1 2 3)))"))
```
is about 10s with the optimization and 12s without it on the JVM. In CLJS 17 vs 19s. This is on a Macbook Air which doesn't have a super powerful processor, but it's noticeable.

In Clojure you see the same effect with direct linking:

```
user=> (alter-var-root #'*compiler-options* (constantly {:direct-linking true}))
{:direct-linking true}
user=> (with-redefs [assoc dissoc] (assoc {:a :b} :a :b))
{:a :b}
```

Maybe sci should support `*compiler-options*` so in babashka you can turn it off for tests and with-redefs will work the way you would expect.

**Comment by borkdude** [comment]
Never mind, I found another optimization which gets back the performance up to the level it was, while fixing this issue.

**Comment by borkdude** [comment]
Should be fixed now in babashka master.

**Comment by cldwalker** [comment]
Thanks!!
