### ISSUE TITLE
Missing clojure.walk/macroexpand-all

### ISSUE THREAD

**Issue by kwrooijen** [borkdude/sci#389]
**Is your feature request related to a problem? Please describe.**
`clojure.walk/macroexpand-all` is not implemented

**Describe the solution you'd like**
For `clojure.walk/macroexpand-all` to be implemented

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/sci/commit/8a57faafa9f69e62c3f8335677d56820c58717a9
