### ISSUE TITLE
Perf consideration: return closures or protocol impls instead of metadata based objects from analyzer

### ISSUE THREAD

**Issue by borkdude** [borkdude/sci#417]
Instead of returning `(with-meta '(+ 1 2 3) {:sci.impl/op :eval-call})` (or similar) from analyzer, we could return:

`(fn [ctx] (eval-call ctx '(+ 1 2 3)))`. In interpreter we would only have to call this function with `ctx` and can then skip checking what to do. Maybe this would help for performance? What do you think @joinr?

**Comment by joinr** [comment]
I think that's probably useful given the bench marking i was seeing (from java 8 though; it's probably better to get a sense of perf costs with JDK 11 and direct linking enabled, then hook up visual vm to confirm what I was seeing).

One thought: if you go this route, then I would (for debugging and similar sanity), probably make a record type that implements IFn, with a single-arity invoke.  Fields could be name, ctx, body.  So you get an inspectable form of the closure if you want to view it, rather than than opaque function.  Performance should be identical.

**Comment by joinr** [comment]
In theory, this optimization would save 1 instance check for IMeta, and a hash lookup (possible involving equiv), and a case dispatch based on the op keyword (another equality check).  That should all get boiled down to an instance check for IFn (or if you go with a record, just check for that type maybe).

**Comment by borkdude** [comment]
We could also return vectors or optimized tuples like `[CONSTANT expr]` where CONSTANT is a number, if that's faster for looking up the right function.

**Comment by borkdude** [comment]
Maybe something like:

``` 
(defprotocol IInterpret
  (interpret [this ctx]))

(deftype Interpret [op expr]
  IInterpret
  (interpret [this ctx]
    (op ctx expr)))
``` 

(although the protocol might include some overhead?)

**Comment by joinr** [comment]
Protocol overhead (if it's not an extended type, but inlined as in deftype/defrecord/reify) is very low actually.  There's almost no benefit from using (.interpret ^IInterpret thing ctx) over (interpret thing ctx) in most cases (I mean there's marginal utility, but it's at the nano level, like 5.x vs 3-4.x, so questionable IME.  Protocols are nice and portable too, with hopefully efficient implementations on other platforms.

**Comment by borkdude** [comment]
Given the above protocol / deftype, I think we can gradually introduce this and benchmark, while also support the other way of doing things, before porting everything.

**Comment by joinr** [comment]
I was looking at just doing that for function calls initially.  You can actually redefine everything in terms of `interpret`, and extend to other types under the legacy implementation.  Might be a little performance hit; another option is to have a special check inside of the sci.impl.interpreter/interpret that looks to see if the thing extends IInterpret, then invokes -interpret if it does.  Or delegate to a cached /memoized version of `satisfies?` that does the same thing (recommend not using built-in clojure memoize, since it's a bit slow for fixed-arity functions and can be easily beaten with a simple implementation).

**Comment by borkdude** [comment]
Just fyi, there was one earlier attempt at this, but then trying to implement a protocol for different types: https://github.com/borkdude/sci/pull/277/files. It's a different approach than the above one.

**Comment by joinr** [comment]
You are going to want to inline the implementation for concrete types, and not rely on `extend` since that will incur a map lookup to check the protocol cache.  That will cost more than instance checks like you're manually doing I think.

**Comment by joinr** [comment]
I take it back, the direct method invocation seems to win, even with an instance check.

For a toy benchmark, if I have

(defprotocol IBlah 
   (blah [this])) 

and an inline type

(defrecord blahrec [x]
   IBlah
   (blah [this] x))

and a function 

(defn eval-blah [x] 
   (cond (instance? user.IBlah x) 
                (.blah ^user.IBlah x) 
             :else (blah x)))

Access times for an instance of the record are like 3ns, where for anything else (via extend) it's about 30+  If you can go entirely into protocol land and eliminate any blending of stuff (e.g. use all custom types with inline protocol impls), then that can be a much faster system.  At the very least, you can establish fast paths and put them up at the top of any concrete checks.

**Comment by ikitommi** [comment]
`satisfies?` is really slow on clojure, see [the issue](https://clojure.atlassian.net/browse/CLJ-1814). To make protocols go fast, the common pattern is to add a protocol method like `-isBlah?`, which returns a boolean and is implemented for all possible classes, e.g. return `false` on unwanted classes - `Object` for Java and `default` for JS. After that, the code looks like:

```clj
(defprotocol Blah
    (-isBlah? [_])
    (-blah [_])

(defn blah [x] (if (-isBlah? x) (-blah x) ... something else...))
```

example in [sieppari](https://github.com/metosin/sieppari/blob/develop/src/sieppari/async.cljc) with `async?`

**Comment by joinr** [comment]
As I mentioned a bit earlier, I typically memoize the call and have a `satisfies?` wrapper that's efficient (not using slow built-in memoize, but a custom variant that avoid RestFn and slow hashing).  That amortizes the cost without much fuss, although you lose a little dynamism (need to invalidate the cache e.g. if you decide to not implement all the stuff at some later point; I typically don't do this unless I am reloading everything, so it's not a problem for me at least).

**Comment by ikitommi** [comment]
@joinr do you have an example of that usage of non-built-in memoize? Is it bounded? soft/weak references? Normal memoize remembers things forever, which is bad if one creates new objects at runtime and those are references forever in the cache,

**Comment by borkdude** [comment]
@ikitommi An example might be Keyword interning where Weakrefs are used:

https://github.com/clojure/clojure/blob/cbb3fdf787a00d3c1443794b97ed7fe4bef8e888/src/jvm/clojure/lang/Keyword.java#L32-L51

**Comment by joinr** [comment]
> @joinr do you have an example of that usage of non-built-in memoize? Is it bounded? soft/weak references? Normal memoize remembers things forever, which is bad if one creates new objects at runtime and those are references forever in the cache,

@ikitommi. The original person who demonstrated a better implementation was Zach Tellman, or at least that's where I got the idea from.  The simplest case is to just replace the memoization container with a concurrent hash map, and performance is substantially better.  Then provide common arities for low order arg functions that turn into lookups into nested maps.  This eliminates structural hashing costs of the varargs version, which can provide additional substantial gains.  Especially for very common functions of 1 or 2 args, this approach is superior.

[Discussion from clj-fast here](https://github.com/bsless/clj-fast/issues/2) walks through examples and corner cases (e.g. no nil allowed in concurrent hash map).  @bsless converged on a sentinel check to work around nil, as well as a nice macro to memoize arbitrary functions.

This particular scheme should preserve the semantics of core memoize, but produce substantially better lookup performance.  That means the limitations (unbounded, strong references, etc) are still a problem.  There is certainly room to blend approaches for managing the cache though, they're just out of scope.  For the motivating examples, the costs on space were infinitesimal.  I think caching protocol satisfaction by class probably fits in that category.  Otoh, many other practical cases would require different semantics (hence something like core.cache).

**Comment by ikitommi** [comment]
Thanks for the pointers, interested in SCI perf and thus this issue, but also need to cook up a fast protocol cache for malli schema creation, will investigate how to do that.

**Comment by borkdude** [comment]
Some ideas worth borrowing here maybe: https://github.com/bsless/contextual

**Comment by borkdude** [comment]
Currently emitting a closure for `if` which made this loop example a lot faster:

```
$ time ./sci "(loop [val 0 cnt 1000000] (if (pos? cnt) (recur (inc val) (dec cnt)) val))"
1000000
./sci    0.97s  user 0.09s system 99% cpu 1.061 total
```

So for code which uses if a lot and has lots of loops, this should mean a significant speed-up, but for typical babashka scripts, I don't see any change.

**Comment by borkdude** [comment]
Btw, I made some bench tooling here:

https://github.com/borkdude/sci#benchmarking
