### ISSUE TITLE
Bug in #js reader tag

### ISSUE THREAD

**Issue by mk** [borkdude/sci#449]
**version**
`0.1.1-alpha.9`
**platform**

JavaScript
**problem**
`#js [1]` evaluated in sci returns a map wrapped in a vector:

<img width="245" alt="CleanShot 2020-11-25 at 10 49 44@2x" src="https://user-images.githubusercontent.com/1187/100211052-f2d31e80-2f0b-11eb-9069-aaa3ad31f3a4.png">

**repro**

(sci/eval-string "#js[1]")

**expected behavior**

```clojure
(sci/eval-string "(= (clj->js [1]) #js[1])")
```
should evaluate to true

**Comment by borkdude** [comment]
@mk Note that

```
cljs.user=> (= (clj->js [1]) #js[1])
false
```
because this is JavaScript :)

**Comment by mk** [comment]
@borkdude oops, good point!

**Comment by borkdude** [comment]
Fixed:

<img width="415" alt="Screenshot 2020-11-25 at 12 06 52" src="https://user-images.githubusercontent.com/284934/100219802-bc4ed100-2f16-11eb-91de-8e5fa0bad931.png">
