### ISSUE TITLE
Consider matching ClojureScript behavior regarding js/

### ISSUE THREAD

**Issue by mk** [borkdude/sci#450]
**Is your feature request related to a problem? Please describe.**
We want to use sci as a replacement for self-hosted cljs. We are passing the options `{:classes {'js goog/global :allow :all}` to `js/` calls working.

One observed difference is property access: `js/document.body.innerHTML` will work in ClojureScript, but return `nil` in sci.

**Describe the solution you'd like**
Allowing me to set an option for sci to make properties work in sci as they do in ClojureScript.

**Describe alternatives you've considered**
Asking users to use propery access, i.e. `(.. js/document -body -innerHTML)` instead of `js/document.body.innerHTML`. For our use case of an online ClojureScript repl the fewer differences in behavior to regular ClojureScript our users need to learn, the better.

**Additional context**
I have not yet found this behavior documented e.g. on https://clojurescript.org/reference/javascript-api but there is at least one reference in the ClojureScript source of it: https://github.com/clojure/clojurescript/blob/0eaa19f4326f02d4dc4e8660ad5f13329b73e3af/src/main/cljs/clojure/browser/repl.cljs#L186

**Comment by mk** [comment]
Some more examples in ClojureScript are:
* `js/Number.MAX_VALUE`
* `js/Number.POSITIVE_INFINITY` 
* ` js/Number.NEGATIVE_INFINITY` https://github.com/clojure/clojurescript/blob/0eaa19f4326f02d4dc4e8660ad5f13329b73e3af/src/main/cljs/cljs/core.cljs#L2346-L2350



* `js/Calculator.add` https://github.com/clojure/clojurescript/blob/0eaa19f4326f02d4dc4e8660ad5f13329b73e3af/src/test/cljs_build/foreign_libs_cljs_2249/core.cljs#L13

I used `ag '(\(| )js/\w+\.\w+'` to find them and filter out function calls like `js/console.log`:

**Comment by borkdude** [comment]
@mk If you haven't found any remaining cases, I'll close the issue for now. Feel free to comment with new cases.
