### ISSUE TITLE
Improve GraalVM docs.

### ISSUE THREAD

**Issue by kkinnear** [borkdude/sci#454]
First, thank you for `sci`.  It is working great to solve a thorny security issue that I have been wrestling with for a long while.  I can see that it took a lot of effort to make it work!

A question: Have you successfully built `[borkdude/sci "0.1.1-alpha.9"]` with graalvm ce 20.3.0?  I am just adding `sci` to zprint, and it builds with graalvm ce 20.0.0 on macos, but fails to build with graalvm ce 20.3.0 on both macos and an Oracle linux docker image with 20.3.0 preloaded.

I noticed that you [reported a similar problem](https://github.com/oracle/graal/issues/2358) with an early version of graalvm ce 20.1.0.  Apparently that was fixed, but I'm seeing something similar when I use `sci` and try to build with 20.3.0.

Here is what I see on macos:

> GraalVM Version 20.3.0 (Java Version 1.8.0_272-b10)
> [zprintm-1.1:28297]    classlist:  12,934.65 ms,  1.47 GB
> [zprintm-1.1:28297]        (cap):   3,589.11 ms,  1.47 GB
> [zprintm-1.1:28297]        setup:  10,612.82 ms,  1.47 GB
> [zprintm-1.1:28297]     (clinit):   2,655.43 ms,  3.87 GB
> [zprintm-1.1:28297]   (typeflow):  51,380.87 ms,  3.87 GB
> [zprintm-1.1:28297]    (objects):  41,179.77 ms,  3.87 GB
> [zprintm-1.1:28297]   (features):   5,110.27 ms,  3.87 GB
> [zprintm-1.1:28297]     analysis: 107,874.13 ms,  3.87 GB
> Error: Unsupported features in 5 methods
> Detailed message:
> Error: Frame states being merged are incompatible: unbalanced monitors - locked objects do not match
>  This frame state: [locals: [1,2,3,1,_,_] stack: [7] locks: [] rethrowException]
> Other frame state: [locals: [1,2,3,1,_,_] stack: [20] locks: [14 / 5] rethrowException]
> Parser context: sci.impl.vars$alter_var_root.invokeStatic(vars.cljc:413) [bci: 11, intrinsic: false]
>   11: getstatic     #2          // __cached_class__1:java.lang.Class
>   14: if_acmpeq     31
>   17: dup           
>   18: instanceof    #24         // sci.impl.vars.IVar
>   21: ifne          116
> 
> Call path from entry point to sci.impl.vars$alter_var_root.invokeStatic(Object, Object, ISeq): 
> 	at sci.impl.vars$alter_var_root.invokeStatic(vars.cljc:411)
> 	at sci.impl.vars$alter_var_root.doInvoke(vars.cljc:411)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 

and on and on and on...

To be clear, I'm not asking you to take any action on this, just wondering if you have successfully used graalvm ce 20.3.0 with `sci`.

Thanks!

**Comment by borkdude** [comment]
@kkinnear Try using `clojure` version `1.10.2-alpha4` in your deps. The locking problem is a typical 1.10.1 and below problem.

**Comment by kkinnear** [comment]
Thank you __so__ much!  That was a variable that I didn't even consider in my search for a solution.  I have tested with `1.10.2-alpha1`, but generally build with `1.9` just to ensure things still work with the older stuff.  Indeed, `1.10.2-alpha4` built great with graalvm 20.3.0 on both macOS and Linux.  Moreover, with Clojure `1.10..2-alpha4` and graalvm `20.3.0` it built in about 1/3 the time as `1.9` and `20.0.0` on macOS -- and took about the same time on Linux (using a docker VM) as macOS, which was a huge change.  It used to take many times longer on Linux.  Once again, thank you for the quick and totally on target response! It would have been a long time, if ever, before I tried that as a solution.

While we are here, thanks again for `sci`.  It is a very neat piece of engineering!

**Comment by borkdude** [comment]
@kkinnear Thanks a lot for your positive feedback. Let me know what you're up to with sci :).

**Comment by borkdude** [comment]
I will take the opportunity to write better docs for this.

**Comment by borkdude** [comment]
TODO:

- [ ] make it clear that for GraalVM you should always use the latest 1.10.2 alpha
- [ ] make it clear that with Java 11 GraalVM you will need the corresponding reflector library

**Comment by agriffis** [comment]
> @kkinnear Thanks a lot for your positive feedback. Let me know what you're up to with sci :).

I can volunteer an answer for this. Kim is the author of [zprint](https://github.com/kkinnear/zprint/), a fantastic library and command-line tool for formatting Clojure.

Zprint can be configured per project, similar to a project-local `.editorconfig` or `.prettierrc`. For more "interesting" configurations, you might need to define a functions in the project-local `.zprintrc`, but we need to be careful about executing untrusted code, say in a git repo cloned from the Internet.

I had written a longer comment describing a trust-based approach [here](https://github.com/kkinnear/zprint/issues/124#issuecomment-576700695) but it's even better if we can load functions with a safe subset of Clojure, then there's no need to configure trusted repos.

**Comment by borkdude** [comment]
@agriffis Thanks for the additional context. Looking forward to having sci integrated in zprint.
