### ISSUE TITLE
How zprint uses sci

### ISSUE THREAD

**Issue by kkinnear** [borkdude/sci#457]
I didn't want to overload your issue for the documentation update, so I started a new "thread" here.

I'm using sci in zprint to read in the options-map.  

Some background -- zprint will read `.zprintrc` files from `~/.zprintrc` as well as a number of other locations.  The `.zprintrc` files contain an options-map, which configures zprint to format source (and structures) in a variety of ways.  Probably too many ways, but that's a conversation for another time.  Anyway, there are several places in the options map where someone can specify a function to receive the current element being formatted and return additions to the current options-map.  People can specify an existing function, but typically they would use the `#( ... )` or `(fn [x] ...)` approach.  When these things are read in from files, there is an obvious security issue, since to get the functions defined we need to evaluate the map.  Someone might fork or clone a github project with a `.zprintrc` file in it, not realize it, and unintentionally have zprint do a `load-string` on a `.zprintrc` file with something malicious (or just plain wrong) in it.  Thus, I had tied off the ability to allow functions in some of the files for security.

In addition, I couldn't even get graalVM to allow people to define functions using `#( ... )` in their `~/.zprintrc` file, which I was assuming secure.  Thus, the whole "define a function to extend the configuration of zprint" approach was really kind of a joke.  Unless I used it in the default options-map, people using the fast graalVM pre-built binaries couldn't really adapt zprint to some of their very specialized approaches.

In the next release I will be using `sci/eval-string` to process the options-maps read in from files, and that will do two things for zprint.  First, the users of graalVM binaries will be able to use functions in options-maps.  Second, I can now allow functions to be used in every `.zprintrc` file, since they can't do anything "bad".  So that is a real plus.

Along those lines, I have been writing the docs for all of this, and I wanted to tell people what functions they could use in the functions they define in options-maps (i.e., what functions are available in sci), since debugging functions in options-maps is already kind of challenging.  I didn't see anything in the sci docs about this, but after some searching I did put this together:

```clojure

(defn sci-namespace
  "Do the keys from one namespace."
  [[k v]]
  {k (into #{} (keys (dissoc v :obj)))})

(defn sci-vars
  "Produce a map of all vars recognized by sci, by namespace."
  []
  (let [namespace-map sci.impl.namespaces/namespaces]
    (apply merge
      {}
      {:macros sci.impl.analyzer/macros}
      (map sci-namespace namespace-map))))

(def scivar (sci-vars))

; zprint will alphabetize sets, which makes the result a bit better

(zprint scivar)
{:macros #{. and as-> case comment declare def defmacro defn do doseq
           expand-constructor expand-dot* fn fn* for if import in-ns lazy-seq
           let loop macroexpand macroexpand-1 new ns or resolve set! try var},
 clojure.core
   #{* *' *err* *file* *in* *ns* *out* *print-length* *print-level* *print-meta*
     *print-namespace-maps* + +' - -' -> ->> -reified-methods .. / < <= = == >
     >= add-watch aget alength alias all-ns alter-meta! alter-var-root ancestors
     any? apply array-map aset assert assoc assoc! assoc-in associative? atom
     bean bigdec bigint biginteger binding binding-conveyor-fn bit-and
     bit-and-not bit-flip bit-not bit-or bit-set bit-shift-left bit-shift-right
     bit-test bit-xor boolean boolean-array boolean? booleans bound?
     bounded-count butlast byte byte-array bytes bytes? cat char char-array
     char-escape-string char-name-string char? chars chunk chunk-append
     chunk-buffer chunk-cons chunk-first chunk-next chunk-rest chunked-seq?
     class class? coll? comp comparator compare compare-and-set! complement
     completing concat cond cond-> cond->> condp conj conj! cons constantly
     contains? count counted? cycle dec dec' decimal? dedupe defmethod defmulti
     defn- defonce defprotocol defrecord delay deliver denominator deref derive
     descendants disj dissoc distinct distinct? doall dorun dotimes doto double
     double-array double? doubles drop drop-last drop-while eduction empty
     empty? ensure-reduced enumeration-seq eval even? every-pred every? ex-cause
     ex-data ex-info ex-message extend extend-protocol extend-type extends?
     false? ffirst filter filterv find find-ns find-var first flatten float
     float-array float? floats flush fn? fnext fnil format frequencies gensym
     get get-in get-method get-thread-binding-frame-impl group-by has-root-impl
     hash hash-map hash-set hash-unordered-coll ident? identical? identity
     if-let if-not if-some ifn? inc inc' indexed? inst? instance? int int-array
     int? integer? interleave intern interpose into into-array ints isa? iterate
     iterator-seq juxt keep keep-indexed key keys keyword keyword? last lazy-cat
     letfn line-seq list list* list? load-string long long-array longs
     make-array make-hierarchy map map-entry? map-indexed map? mapcat mapv max
     max-key memoize merge merge-with meta methods min min-key mod
     multi-fn-add-method-impl multi-fn-impl multi-fn?-impl munge name namespace
     namespace-munge nat-int? neg-int? neg? newline next nfirst nil? nnext not
     not-any? not-empty not-every? not= ns-aliases ns-imports ns-interns ns-map
     ns-name ns-publics ns-refers ns-resolve ns-unmap nth nthnext nthrest num
     number? numerator object-array odd? parents partial partition partition-all
     partition-by peek persistent! pop pop-thread-bindings pos-int? pos? pr
     pr-str prefer-method prefers print print-dup print-method print-str printf
     println prn prn-str promise protocol-type-impl push-thread-bindings
     qualified-ident? qualified-keyword? qualified-symbol? quot rand rand-int
     rand-nth random-sample range ratio? rational? rationalize re-find re-groups
     re-matcher re-matches re-pattern re-seq read read-line read-string
     realized? record? reduce reduce-kv reduced reduced? reductions refer reify
     reify* rem remove remove-all-methods remove-method remove-ns remove-watch
     repeat repeatedly replace replicate require requiring-resolve reset!
     reset-meta! reset-thread-binding-frame-impl reset-vals! resolve rest
     reverse reversible? rseq rsubseq run! satisfies? second select-keys seq
     seq? seqable? seque sequence sequential? set set? short short-array shorts
     shuffle simple-ident? simple-keyword? simple-symbol? some some-> some->>
     some-fn some? sort sort-by sorted-map sorted-map-by sorted-set
     sorted-set-by sorted? special-symbol? split-at split-with str string? subs
     subseq subvec supers swap! swap-vals! symbol symbol? tagged-literal
     tagged-literal? take take-last take-nth take-while the-ns to-array
     trampoline transduce transient tree-seq true? type unchecked-add
     unchecked-add-int unchecked-byte unchecked-char unchecked-dec-int
     unchecked-divide-int unchecked-double unchecked-float unchecked-inc
     unchecked-inc-int unchecked-int unchecked-long unchecked-multiply
     unchecked-multiply-int unchecked-negate unchecked-negate-int
     unchecked-remainder-int unchecked-short unchecked-subtract
     unchecked-subtract-int underive unquote unreduced unsigned-bit-shift-right
     update update-in uri? use uuid? val vals var? vary-meta vec vector vector?
     volatile! vreset! vswap! when when-first when-let when-not when-some while
     with-bindings with-in-str with-meta with-open with-out-str with-redefs
     with-redefs-fn xml-seq zero? zipmap},
 clojure.edn #{read read-string},
 clojure.lang #{IAtom IAtom2 IDeref compareAndSet deref reset resetVals swap
                swapVals},
 clojure.repl #{apropos demunge dir dir-fn doc find-doc print-doc pst source
                source-fn stack-element-str},
 clojure.set #{difference index intersection join map-invert project rename
               rename-keys select subset? superset? union},
 clojure.string #{blank? capitalize ends-with? escape includes? index-of join
                  last-index-of lower-case re-quote-replacement replace
                  replace-first reverse split split-lines starts-with? trim
                  trim-newline triml trimr upper-case},
 clojure.template #{apply-template do-template},
 clojure.walk #{keywordize-keys macroexpand-all postwalk postwalk-demo
                postwalk-replace prewalk prewalk-demo prewalk-replace
                stringify-keys walk}}
```
The above structure is what I intend to put in my docs about what you can do with sci.  If I've missed something obvious, I'd love to know about it.  All of the functions that I use are in there, but the above data only comes from a very brief skim of the source of sci.

Anyway, that is probably more than you wanted to know about how zprint is going to use sci.  Thanks for asking!

Curiously, while I've tried really hard to limit the dependencies for zprint (particularly for those using it as a library), the only dependency that it has these days, beside `rewrite-clj(s)`, is `edamame`, and now it will have`sci`.  It uses edamame to scan a file to find the breaks between top level expressions, so that it can implement formatting a range of lines -- and move the range specifications around so that they don't fall into the middle of expressions, which would break the formatting.  Once it figures out the range, it uses rewrite-clj(s) to do the actual detailed formatting.   It only uses edamame when someone actually specifies a range, so it doesn't always parse the whole file twice.  I haven't given much though to using edamame as the only parser, since zprint is pretty intimately tied to the zipper structure produced by rewrite-clj.   The internal formatting engine in zprint formats structures at the repl and source parsed by rewrite-clj largely without knowing which one it is operating on.  Which is more than you probably wanted to know as well, but I thought it was interesting that you have produced the only two dependencies beyond the basic parser that zprint uses.  Thanks for them both!

As an aside, I stumbled on `puget-cli` the other day.  Interestingly enough, the pre-built zprint binaries will colorize `.edn` to the terminal, though I've never documented that:
```clojure
./zprintm-1.0.2 '{:color? true}'  <helloworld.clj
"Hello World!"
```
The "Hello World"" would be in color, though that doesn't come through in the markdown here.

You probably like the puget output or colors or something, but I suppose I should document this in case someone who likes zprint would like to do it too.

That is certainly enough for now!

**Comment by borkdude** [comment]
@kkinnear Thanks a lot for explaining! I will add you to the README in sci of projects using sci, if you don't mind.

I've never given such an explicit overview of all the available functions in sci, but I usually explain it like: all the pure functions from clojure.core (and clojure.set, clojure.string) that are (probably) safe to execute in configuration / sandboxed environments. In babashka (which is using sci) I add the unsafe functions / namespaces as well since in a scripting environment you want to have full control.

> You probably like the puget output or colors or something

I made the puget CLI when someone asked if I could ask puget to babashka. I showed how this was a more composable solution since any tools that can output EDN (such as jet, the clojure CLI, etc, etc) can now get colorization. Also it saves me a few megabyte of binary size in babashka to do it this way.

**Comment by kkinnear** [comment]
Adding zprint to the readme of projects using sci would be great, thanks!

**Comment by borkdude** [comment]
@kkinnear I'll add it as soon you've merged your sci code to master and/or released the binary. Until then let's keep this issue open.

**Comment by kkinnear** [comment]
I released `zprint "1.1.0"` yesterday which uses `sci`.  It worked out really well, `sci` just worked! `zprint` also uses `edamame` explicitly,  independent of the use of `edamame` in `sci`, if that is interesting to note on the `edamame` README.md page (as I noticed some other projects there).

**Comment by borkdude** [comment]
@kkinnear Yes, PR to edamame readme welcome!

**Comment by borkdude** [comment]
And congrats on the 1.1.0 release!

**Comment by borkdude** [comment]
Btw, PR to the sci README also welcome as it's released now.

**Comment by borkdude** [comment]
I think we can now close this issue, but feel free to leave it open until you have PR-ed edamame.
