### ISSUE TITLE
SciVar can not be encoded as transit

### ISSUE THREAD

**Issue by kommen** [borkdude/sci#487]
**version**

0.2.0

**platform**

Javascript, Browser

**problem**

Exception when serializing a  `SciVar` to transit:

```
TypeError: x.cljs$core$IWithMeta$_with_meta$arity$2 is not a function
```

**repro**

Pass an instance of `SciVar` to `cognitect.transit/write`

**expected behavior**

A `SciVar` can be encoded to transit the same as `cljs.core/Var`.

**Discussion**

The code in which the exception is thrown:

```js
cognitect.transit.write_meta = (function cognitect$transit$write_meta(x){
if((((!((x == null))))?(((((x.cljs$lang$protocol_mask$partition0$ & (131072))) || ((cljs.core.PROTOCOL_SENTINEL === x.cljs$core$IMeta$))))?true:false):false)){
var m = x.cljs$core$IMeta$_meta$arity$1(null);
if((!((m == null)))){
return (new cognitect.transit.WithMeta(x.cljs$core$IWithMeta$_with_meta$arity$2(null,null),m));
} else {
return x;
}
} else {
return x;
}
```

My suspicion is that `SciVar` would need to implement `IWithMeta` like `cljs.core/Var` does here:
https://github.com/clojure/clojurescript/blob/5e88d3383e0f950c4de410d3d6ee11769f3714f4/src/main/cljs/cljs/core.cljs#L1143-L1145

**Comment by borkdude** [comment]
@kommen What is the use case for serializing a var? This isn't possible in JVM Clojure either as far as I know?

```
user=> (transit/write writer 1)
nil
user=> (transit/write writer 2)
nil
user=> (transit/write writer #'inc)
Execution error (NullPointerException) at com.cognitect.transit.impl.AbstractEmitter/marshalTop (AbstractEmitter.java:203).
null
```

**Comment by kommen** [comment]
@borkdude thanks for having a look. We ran into this when sending eval results from a worker iframe to the main app, for which we encode these results to transit. But it turned out it was a diffent issue on our side.

**Comment by mk** [comment]
Actually, looking into this further, we do think there's an issue still: we cannot transit encode a SciVar in ClojureScript, even with a custom handler for the type:

```clojure
(require '[cognitect.transit :as transit]
         '[sci.impl.vars :refer [SciVar]]
         '[sci.core :as sci])

(deftype SciVarTransitHandler []
  Object
  (tag [this v] "var")
  (rep [this v] :var))

(def sci-var
  (sci/eval-form (sci/init {}) '(def a :hello)))

(def writer-with-meta
  (transit/writer :json {:handlers {SciVar (SciVarTransitHandler.)}
                         :transform transit/write-meta}))

(def writer-without-meta
  (transit/writer :json {:handlers {SciVar (SciVarTransitHandler.)}}))

(transit/write writer-without-meta sci-var);; => "[\"~#var\",\"~:var\"]"
(transit/write writer-with-meta sci-var) ;; => #object[TypeError TypeError: x.cljs$core$IWithMeta$_with_meta$arity$2 is not a function]
```

**Comment by borkdude** [comment]
@mk @kommen 

I still don't have an answer as to why you would want to do this.

See https://github.com/borkdude/sci/issues/487#issuecomment-749149364

Why are you not simply deref-ing the var before serialization? What if the var contains a function? Functions can't be serialized either?

**Comment by mk** [comment]
In Clojure, we have code like this:
```clojure
(require '[cognitect.transit :as transit])
(def out (java.io.ByteArrayOutputStream. 4096))

(def test-var :hello)

(defn write-var [v]
  (symbol (str (.getName (:ns (meta v))) "/" (:name (meta v)))))

(def writer
  (transit/writer out :json {:handlers {clojure.lang.Var
                                        (transit/write-handler "var" write-var)}}))

(transit/write writer 1)
(transit/write writer 2)
(transit/write writer #'test-var)
```

So we would like to handle vars at the serialization layer instead of doing a preprocessing step.

**Comment by borkdude** [comment]
@mk Why does CLJS have something regarding `writer-with-meta` which you are not using in the CLJ implementation for vars? Can I see docs on this?

**Comment by mk** [comment]
@borkdude this is support in transit-cljs for writing metadata that was added in https://github.com/cognitect/transit-cljs/commit/35663b35e42fb0d58d800428d3dbb1a8a6da90a1. The same was added for transit-clj in https://github.com/cognitect/transit-clj/commit/a823f3b418e535232fa48f0b73ac8e32c4818863.

**Comment by borkdude** [comment]
@mk Sci vars follow the JVM semantics.

``` 
user=> (meta (with-meta #'inc {:a 1}))
Execution error (ClassCastException) at user/eval1 (REPL:1).
class clojure.lang.Var cannot be cast to class clojure.lang.IObj (clojure.lang.Var and clojure.lang.IObj are in unnamed module of loader 'app')
``` 

As such they do not allow `with-meta` since Vars are not immutable objects. That might be the cause of the issue, it's just my guess by looking at the error message.

You haven't answered my question why you are not using the metadata facility of transit in your above code in CLJ, but you are in CLJS. Why do you need it in CLJS but not in CLJ?

**Comment by mk** [comment]
> why you are not using the metadata facility of transit in your above code in CLJ, but you are in CLJS. Why do you need it in CLJS but not in CLJ?

We are, my comment in https://github.com/borkdude/sci/issues/487#issuecomment-775956017 was in response to _This isn't possible in JVM Clojure either as far as I know?_.

So our actual Clojure code has a writer like this
```clojure
(def writer
  (transit/writer out :json {:handlers {clojure.lang.Var
                                        (transit/write-handler "var" write-var)}
                             :transform transit/write-meta}))
```

**Comment by borkdude** [comment]
@mk On this line:

https://github.com/cognitect/transit-cljs/commit/35663b35e42fb0d58d800428d3dbb1a8a6da90a1#diff-dc4ef2f4efc2bcb1a0763196e444805dd02d40fc1e5c017b816e4d08ad11e509R411

they are calling `-with-meta` on something which only has been verified to be a `IMeta`. I think this should be `IWithMeta`. SciVar implements `IMeta` but not `IWithMeta` which is a conscious design decision.

**Comment by mk** [comment]
@borkdude you're right. I think I have everything to get things working and will file an upstream issue with transit-cljs. Thanks for helping me figure this out!
