### ISSUE TITLE
type should return something else than PersistentMap for defrecord?

### ISSUE THREAD

**Issue by borkdude** [borkdude/sci#492]
```
(defrecord Foo []) (type (Foo.))
```

In Clojure a `Class` is returned:

```
user=> (defrecord Foo [])
user.Foo
user=> (type (type (Foo.)))
java.lang.Class
```

In ClojureScript a function is returned:

```
cljs.user=> (defrecord Foo [])
cljs.user/Foo
cljs.user=> (type (type (Foo.)))
#object[Function]
```

I'm not sure what to return in sci, because it does not define classes like Clojure.

**Comment by mk** [comment]
For our use case, it would be sufficient, if we had some way, of getting to the fully-qualified class name.

In Clojure this works:
```clojure
(ns user)
(defrecord R [foo])
(-> "bar" ->R type .getCanonicalName) ;; => "user.R" 
```

In sci:
```clojure
(ns user)
(defrecord R [foo])
(-> "bar" ->R meta :sci.impl/type str) ;; => "R"
```

**Comment by mk** [comment]
I've added a failing test in #493 but haven't been able to get it working yet.

**Comment by borkdude** [comment]
@mk Thanks. I'll have a look during the weekend, hopefully.

**Comment by borkdude** [comment]
@mk How would you tackle this for normal CLJS?

**Comment by borkdude** [comment]
@mk In branch `record-type`, commit a40d4a7586f68df5bed4d16e01c3cc7e627090cc, this works:

```
$ lein run -m sci.impl.main "(ns foo) (defrecord Foo []) (type (Foo.))"
foo/Foo
```

Note that `type` returns a symbol here and not a class, like in Clojure. Also it's namespaced, not dotted. Not sure if that matters?

**Comment by borkdude** [comment]
@mk I found in clara rules how they solve this for CLJS:

``` clojure
(ns foo)

(defrecord Foo [])

(derive Foo ::system-type)

(isa? (type (Foo.)) ::system-type)
```

I think that could be a useful way to not rely on the specifics of the return value of `type` but still get the information you need out of it. I wrote a test for this in sci now (in the branch).

**Comment by borkdude** [comment]
@mk With the changes just merged to master it should now be possible to do what you want.
