### ISSUE TITLE
Typehint confuses CLJS compiler

### ISSUE THREAD

**Issue by thheller** [borkdude/sci#499]
https://github.com/borkdude/sci/blob/472ca74041f082f86e7f8cb1d9f2dafa3492d40c/src/sci/impl/fns.cljc#L118

The `^clojure.lang.Associative` hint is sort of invalid for CLJS and leads to a bunch (35+) of

```
------ WARNING #4 - :undeclared-var --------------------------------------------
 File: ../sci/src/sci/impl/fns.cljc:141:28
--------------------------------------------------------------------------------
 138 |                     (if recur? (recur) ret)))
 139 |               1 #?(:clj (gen-fn 1)
 140 |                    :cljs (if disable-arity-checks?
 141 |                            (gen-fn 1 true)
----------------------------------^---------------------------------------------
 Use of undeclared Var sci.impl.fns/clojure
--------------------------------------------------------------------------------
 142 |                            (gen-fn 1 false)))
 143 |               2 #?(:clj (gen-fn 2)
 144 |                    :cljs (if disable-arity-checks?
 145 |                            (gen-fn 2 true)
--------------------------------------------------------------------------------
```

warnings when compiling with `shadow-cljs`. The errors however originate in the actual CLJS compiler, it just doesn't display those warnings since it treats all dotted symbols as valid. They are however not valid and will confuse the type inference logic since it introduces an unknown type. I'm not sure the typehint does anything useful here anyways so it might be good to remove it or create a proper `#?(:clj ... :cljs ...)` conditional so this CLJ specific info doesn't leak into the CLJS compilation.

**Comment by borkdude** [comment]
Hi @thheller, thanks for the issue.

This has already been reported in:
https://github.com/borkdude/sci/issues/435

but your information describes the issue better. I'll close the other one.

**Comment by borkdude** [comment]
Should be fixed with https://github.com/borkdude/sci/commit/fe9ba20a9713733a5f3245f335c14ad4a75d5879
