### ISSUE TITLE
Destructuring first argument of record's method does not work as expected (inconsistent with clojure 1.10.1)

### ISSUE THREAD

**Issue by charignon** [borkdude/sci#512]
First and foremost, thank you so much @borkdude for all of your work, you brought the joy of clojure to scripting with your projects! 

This is a bug report when trying to run some code under Babashka; the code worked with Clojure 1.10.1 but failed with Babashka.

I am using Babashka v0.2.7 , Linux Binary Distribution, which maps to version 0.2.2-SNAPSHOT of sci, hash *f724f0e9f5bcb8b19f17b6b96017dafefec67cf4*

### Minimal code to repro the issue:
```clojure
(defprotocol Foo (sayhello [_ name] "print a name"))
(defrecord Greeter [state] Foo (sayhello [{:keys [state]} name] (println state name)))
(sayhello (Greeter. "test") "john")
```

### Clojure 1.10.1

```clojure
$ clojure
Clojure 1.10.1:
user=> (defprotocol Foo (sayhello [_ name] "print a name"))
Foo
user=> (defrecord Greeter [state] Foo (sayhello [{:keys [state]} name] (println state name)))
user.Greeter
user=> (sayhello (Greeter. "test") "john")
test john
nil
```
### Babashka v0.2.7:
```clojure
$ bb
Babashka v0.2.7 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (defprotocol Foo (sayhello [_ name] "print a name"))
{:ns #object[sci.impl.vars.SciNamespace 0x57cba1e5 "user"], :methods #{#object[clojure.lang.MultiFn 0x1f6925bf "clojure.lang.MultiFn@1f6925bf"]}}
user=> (defrecord Greeter [state] Foo (sayhello [{:keys [state]} name] (println state name)))
#object[clojure.lang.MultiFn 0x1f6925bf "clojure.lang.MultiFn@1f6925bf"]
user=> (sayhello (Greeter. "test") "john")
nil john
nil
```
**expected behavior:** I would expect Babashka to print "test john" and not "nil john".

There is a workaround and records are not broken (see defrecord tests in this repo), but it may trip someone who is trying to convert code from clojure to babashka/sci.

**Comment by borkdude** [comment]
Thanks, I'll look into it!

**Comment by borkdude** [comment]
The bug is that destructuring isn't accounted for in the defrecord implementation, but this works:

```
(defrecord Greeter
    [state] Foo
    (sayhello [rec name]
      (let [{:keys [state]} rec]
        (println state name))))
```

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/sci/commit/735527b41aa9bae9f8b26fbe6a235335269590ac
