### ISSUE TITLE
Metadata contains :sci.impl/op key

### ISSUE THREAD

**Issue by mk** [borkdude/sci#555]
**version**
master at e8374356c0751bbacde380aa742660e76f20eb10

**problem**
Extra `:sci.impl/op` key on metadata.

**repro**
```clojure
(sci/eval-string "(meta ^:m {:foo {}})")
;;=> {:m true, :sci.impl/op :eval} 
```
-------------------
Changed description after https://github.com/borkdude/sci/issues/555#issuecomment-811087993, original issue here for context:
**version**
0.2.4 and ~~master at e8374356c0751bbacde380aa742660e76f20eb10~~

**problem**
Metadata isn't preserved correctly on e.g. nested maps.

**repro**
```clojure
(sci/eval-string "(meta ^:m {:foo :bar})") ;; => {:m true}  
(sci/eval-string "(meta ^:m {:foo {}})") ;; => nil
```

**Comment by mk** [comment]
I've added a failing test to illustrate the problem in https://github.com/borkdude/sci/commit/01c734f4532d7775de23319958787aea34efc716.

**Comment by borkdude** [comment]
@mk I'm getting:

```
user=> (sci/eval-string "(meta ^:m {:foo {}})")
{:m true, :sci.impl/op :eval}
```
on master (the `:sci.impl/op :eval` should probably not be there).

**Comment by borkdude** [comment]
Is this on CLJS or CLJ?

**Comment by borkdude** [comment]
OK, can reproduce by adding the failing tests, to branch: issue-555-meta-nested-maps

**Comment by borkdude** [comment]
@mk Note that these tests do pass:

```
(testing "meta on nested maps"
    (is (:m (eval* "(meta ^:m {:foo :bar})")))
    (is (:m (eval* "(meta ^:m {:foo {}})"))))
 ``` 
 so although there is an extra key, I can't reproduce your original issue.

**Comment by mk** [comment]
You're right, I'm just able to reproduce the behavior as above under 0.2.3 and 0.2.4 (like seen below) but not on master. I thought master was broken because of the test failure but it only failed because of the `:sci.impl/op` key like you've written above.

<img width="243" alt="CleanShot 2021-03-31 at 15 46 18@2x" src="https://user-images.githubusercontent.com/1187/113154729-97f26080-9238-11eb-87ab-92be4851201e.png">

I've bisected and identified baf61ab5c46b622d10a71c4f489a35a9b32696cb as the commit that fixed it. So I think this can be closed as a duplicate of #546.

Do you want me to maybe create an extra issue for removing the `:sci.impl/op` key from metadata?

**Comment by borkdude** [comment]
Let's just change the title of this issue... done. Feel free to update the original post.

**Comment by borkdude** [comment]
@mk Fixed!

**Comment by mk** [comment]
@borkdude thank you!
