### ISSUE TITLE
Don't convert Clojure values to JS values automatically in interop

### ISSUE THREAD

**Issue by borkdude** [borkdude/sci#602]
E.g. this doesn't work correctly because of it:

``` clojure
(.then (.resolve js/Promise {:a 1}) (clojure.core/fn [{:keys [:a] :as m}] a))
```

/cc @jeroenvandijk I'm changing this behavior, I didn't realize SCI was doing this, but just FYI, in case you're relying on it somewhere.

**Comment by jeroenvandijk** [comment]
@borkdude Thanks for the heads up!

I'm not actively using this as far as I know. I was experimenting mostly and for a reason I don't remember this was how I solved it. This was last year when it was probably just me trying some first things. I'm sure there are more people pushing the JS Sci limits now!

Also I don't remember this line [in interop.cljc](https://github.com/borkdude/sci/blob/master/src/sci/impl/interop.cljc#L72-L73)

I'll update one project to the new Sci soon and see what happens :)

**Comment by borkdude** [comment]
Thanks!
