### ISSUE TITLE
Allow `pr-str` to be used

### ISSUE THREAD

**Issue by ikitommi** [borkdude/sci#90]
```clj
(sci/eval-string "(pr-str \"kikka\")")
; Syntax error (ExceptionInfo) compiling at ...
; Could not resolve symbol: pr-str [at line 1, column 2]
```

**Comment by borkdude** [comment]
@ikitommi The sci does not allow side-effecting functions by default, this is up to the library consumer and you can enable it with:

```
(sci/eval-string "(pr-str \"kikka\")" {:bindings {'pr-str pr-str}})
```

**Comment by ikitommi** [comment]
Is `pr-str` considered side-effecting because it internally uses print (but prints it to a StringBuffer)? For user perspective, it just returns a String.

**Comment by borkdude** [comment]
Oh, you are right. Sorry about that. I'll accept a PR for pr-str.

**Comment by borkdude** [comment]
This can be added here:

https://github.com/borkdude/sci/blob/master/src/sci/impl/namespaces.cljc#L180

**Comment by borkdude** [comment]
Fixed on master.
